const SIGN_IN = 'SIGN_IN';
const SIGN_UP = 'SIGN_UP';
const AUTH_START = 'AUTH_START'
const AUTH_SUCCESS = 'AUTH_SUCCESS';
const AUTH_FAIL = 'AUTH_FAIL';
const AUTH_LOGOUT = 'AUTH_LOGOUT'
const CLEAR_ERROR = 'CLEAR_ERROR';
const LOG_OUT = 'LOG_OUT';

export const ADD_EXERCISE = 'ADD_EXERCISE';
export const SET_EXERCISES = 'SET_EXERCISES';
export const RESET_EXERCISES = 'RESET_EXERCISES';
export const REMOVE_EXERCISE = 'REMOVE_EXERCISE';
export const EDIT_EXERCISE = 'EDIT_EXERCISE';
export const TOGGLE_LOAD = 'TOGGLE_LOAD';

export const SET_CURRENT = 'SET_CURRENT';
export const ADD_ENTRY = 'ADD_ENTRY';
export const DELETE_ENTRY = 'DELETE_ENTRY';
export const ADD_SET = 'ADD_SET';
export const DELETE_SET = 'DELETE_SET';
export const SAVE_PREFS = 'SAVE_PREFS';

export { SIGN_IN, SIGN_UP, AUTH_START, AUTH_FAIL, AUTH_SUCCESS, AUTH_LOGOUT, CLEAR_ERROR, LOG_OUT };